function [Fx,Fy] = Dugoff(Cx,Cy,Fn,s,alpha,U,mu0,eps)
% This function returns a vector [Fx, Fy] of the force generated by a tire 
% with a Dugoff tire model.
%   Cx: Cornering stiffness
%   Cy: Longitudinal stiffness
%   Fn: Normal force of the tire
%   s: wheel slip
%   alpha: slip angle
%   U: velocity of the vehicle
%   mu0: friction force coefficient of the tire road interaction
%   eps: parameter dependent on the road tire interface

mu  = mu0 * (1 - eps*U*abs(s));
if abs(s) == 1
    Fx = sign(s)*(Cx * mu * Fn)/sqrt((Cx)^2+(Cy*tan(alpha))^2);
    Fy = (Cy * tan(alpha) * mu * Fn)/sqrt((Cx)^2+(Cy*tan(alpha))^2);
else
    Fxd = Cx * s / abs(1-abs(s));
    Fyd = tan(alpha) / abs(1-abs(s));
    lambda = mu / (2 * sqrt((Fxd/Fn)^2 + (Fyd/Fn)^2));
    if lambda > 1
        % No saturation
        Fx = Fxd;
        Fy = Fyd;
    else
        % Saturation
        Fx = Fxd * 2 * lambda * (1 - lambda/2);
        Fy = Fyd * 2 * lambda * (1 - lambda/2);
    end
end



end
