clear; clc;
close all;

%% Load vehicle parameters
run parameters.m

Gc = load('Youla_controller.mat','Gc');
Gc = Gc.Gc;

%% Define initial conditions
U_0 = 30/3.6;
chassis_state_init   = [U_0 0 0 U_0/rw U_0/rw U_0/rw U_0/rw 0 0 0];
rear_axle_state_init = [G*U_0/rw 0];

%% Set sensor parameters
Ts_sensor = 0.001;  % Sampling time of the sensors
sigma_ax  = 0.5;    % Covariance of accelerometers
sigma_wij = 0.1;    % Covariance of wheel speed sensors

%% Set parameters of EKF and UKF
Ts_EKF = 0.001;
Ts_UKF = 0.001;
Qk_EKF = eye(1)/1000000;
Qk_UKF = eye(5)/1000000;
Rk = diag([sigma_ax sigma_wij sigma_wij]);

set_param('model/EKF',...
    'x_init',strcat('[',num2str(0),';',...
        num2str(U_0/rw*G),';',...
        num2str(U_0/rw),';',...
        num2str(U_0/rw),';',...
        num2str(U_0),']'),...
    'Ts'   ,num2str(Ts_EKF),...
    'K_hsf',num2str(K_hsf),...
    'b_hsf',num2str(b_hsf),...
    'G'    ,num2str(G),...
    'Jm_R' ,num2str(Jm_R),...
    'Jw'   ,num2str(Jw),...
    'rw'   ,num2str(rw_est),...
    'm'    ,num2str(m_est),...
    'c1'   ,num2str(c1_est),...
    'c2'   ,num2str(c2_est),...
    'c3'   ,num2str(c3_est),...
    'fRLz0',num2str(fRLz0_est),...
    'fRRz0',num2str(fRRz0_est),...
    'CRx'  ,num2str(CRx_est),...
    'muRL0',num2str(muRL0_est),...
    'muRR0',num2str(muRR0_est),...
    'epsDugoff',num2str(epsDugoff_est))

set_param('model/UKF',...
    'x_init',strcat('[',num2str(0),';',...
        num2str(U_0/rw*G),';',...
        num2str(U_0/rw),';',...
        num2str(U_0/rw),';',...
        num2str(U_0),']'),...
    'Ts'   ,num2str(Ts_UKF),...
    'K_hsf',num2str(K_hsf),...
    'b_hsf',num2str(b_hsf),...
    'G'    ,num2str(G),...
    'Jm_R' ,num2str(Jm_R),...
    'Jw'   ,num2str(Jw),...
    'rw'   ,num2str(rw_est),...
    'm'    ,num2str(m_est),...
    'c1'   ,num2str(c1_est),...
    'c2'   ,num2str(c2_est),...
    'c3'   ,num2str(c3_est),...
    'fRLz0',num2str(fRLz0_est),...
    'fRRz0',num2str(fRRz0_est),...
    'CRx'  ,num2str(CRx_est),...
    'muRL0',num2str(muRL0_est),...
    'muRR0',num2str(muRR0_est),...
    'epsDugoff',num2str(epsDugoff_est))

%% Run simulation
engine_torque = 200;
maneuver = 'none';
maneuver_nb = getManeuver(maneuver);
disp(['Initial velocity: ',num2str(3.6*U_0),' km/h'])
disp(['Road inclination: ',num2str(100*tan(alpha)),'m / 100m'])
disp(['Maneuver: ',maneuver])
sim('model')

% % Increase m by 20%
% m = 1.2*m;
% fFLz0 = m*g*b/(2*l); % Static normal force on the FR wheel (N)
% fFRz0 = m*g*b/(2*l); % Static normal force on the FL wheel (N)
% fRLz0 = m*g*a/(2*l); % Static normal force on the RL wheel (N)
% fRRz0 = m*g*a/(2*l); % Static normal force on the RR wheel (N)
% DFx   = m*h/(2*l);   % Level arm due to longitudinal acceleration (m)
% DFFy  = m*h*b/(T*l); % Level arm due to lateral acceleration front axle (m)
% DFRy  = m*h*a/(T*l); % Level arm due to lateral acceleration rear axle (m)

%% Plot results
figure(1)
hold on
box on
plotErrorPDF(EKF.fRLx,fijx_true.fRLx,1000)
plotErrorPDF(UKF.fRLx,fijx_true.fRLx,1000)
plotErrorPDF(Youla.fRLx,fijx_true.fRLx,1000)
legend('EKF','UKF','Youla')

